-- =============================================================================
-- DEPRECADO — este seed manual (pegar 3 UIDs a mano) fue reemplazado por el
-- seed DETERMINISTA auto-run en `supabase/seed.sql`, que:
--   • crea los usuarios de auth (con password) + identities con UUIDs fijos,
--   • siembra 2 talleres + fixtures de los 4 targets de la rebanada real-JWT,
--   • lo corre automáticamente `supabase db reset` (config.toml [db.seed]).
--
-- Para sembrar el stack local: `supabase db reset`  (o `./scripts/seed-test.sh`
-- que además emite `.env.integration` para el FE).
--
-- Se conserva este archivo solo como puntero; no lo corre nada.
-- =============================================================================
